# Generated by Django 2.2.2 on 2019-10-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='title',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='titleee',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
