# Generated by Django 2.2.2 on 2019-08-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_auto_20190803_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_options_values',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True,
                                      verbose_name='Price of an option'),
        ),
    ]
