# Generated by Django 2.2.2 on 2019-10-25 16:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_auto_20191025_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='titleee',
            new_name='title',
        ),
    ]
