# Generated by Django 2.2.2 on 2019-10-25 16:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_auto_20191025_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='title',
        ),
    ]
