# Generated by Django 2.2.2 on 2019-08-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_auto_20190803_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='societe',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='tva',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
