# Generated by Django 2.2.2 on 2019-08-03 16:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0005_auto_20190803_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='timestamp',
            new_name='expire_date',
        ),
        migrations.RemoveField(
            model_name='bannerhistory',
            name='banners_shown',
        ),
        migrations.AddField(
            model_name='banner',
            name='show_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bannerhistory',
            name='banner_clicked',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bannerhistory',
            name='banner_shown',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('shipping_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                           to='core.Image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='deliverymethod',
            name='payment_methods',
            field=models.ManyToManyField(related_name='delivery_methods', to='core.PaymentMethod'),
        ),
    ]
