# Generated by Django 2.2.2 on 2019-10-25 19:42

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0005_newsletter_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
