# Generated by Django 2.2.2 on 2019-08-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0006_auto_20190803_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='shipping_price',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='PaymentOptions',
            field=models.CharField(choices=[('0', '0'), ('liv', 'livraison'), ('100', '100%')], default='100',
                                   max_length=3),
        ),
    ]
