# Generated by Django 2.2.2 on 2019-10-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0006_auto_20191025_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletteremail',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
