# Generated by Django 2.2.2 on 2019-10-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0007_newsletteremail_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
