# Generated by Django 2.2.2 on 2019-10-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0008_contact_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='complete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
