# Generated by Django 2.2.2 on 2019-08-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0008_auto_20190803_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverymethod',
            name='payment_methods',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='payment_options',
        ),
        migrations.AddField(
            model_name='deliverymethod',
            name='payment_options',
            field=models.ManyToManyField(related_name='delivery_methods', to='core.PaymentOptions'),
        ),
        migrations.AddField(
            model_name='paymentoptions',
            name='payment_method',
            field=models.ManyToManyField(related_name='payment_options', to='core.PaymentOptions'),
        ),
    ]
