# Generated by Django 2.2.2 on 2019-08-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0009_auto_20190803_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentoptions',
            name='payment_method',
            field=models.ManyToManyField(related_name='payment_options', to='core.PaymentMethod'),
        ),
    ]
