# Generated by Django 2.2.2 on 2019-08-03 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0010_auto_20190803_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.PaymentOptions'),
        ),
    ]
