# Generated by Django 2.2.2 on 2019-08-03 20:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0011_order_payment_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordoered',
        ),
    ]
