# Generated by Django 2.2.2 on 2019-11-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191106_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_clicked',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_shown',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='BannerHistory',
        ),
    ]
