# Generated by Django 2.2.2 on 2019-08-03 21:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0012_remove_order_ordoered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentoptions',
            old_name='payment_method',
            new_name='payment_methods',
        ),
    ]
